name: Compile RealSR-NCNN-Android-CLI

on:
  repository_dispatch:
  workflow_dispatch:
env:
  CI_NAME: Custom CI
  ASSETS_URL: https://github.com/tumuyan/RealSR-NCNN-Android/releases/download/1.9.6/assets.zip
  NCNN_URL: https://github.com/Tencent/ncnn/releases/download/20241226/ncnn-20241226-android-vulkan-shared.zip
  NCNN_NAME: ncnn-20241226-android-vulkan-shared.zip
  OpenCV_DIR: /usr/local/lib/cmake/opencv4
  CMAKE_PREFIX_PATH: /usr/local

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
      with:
        submodules: recursive  # 确保子模块被克隆

    - name: Cache OpenCV build
      uses: actions/cache@v4
      id: cache-opencv
      with:
        path: |
          opencv/build
          opencv_contrib
        key: ${{ runner.os }}-opencv-4.9.0-${{ hashFiles('opencv/CMakeLists.txt') }}

    - name: Cache ncnn
      uses: actions/cache@v4
      id: cache-ncnn
      with:
        path: 3rdparty/ncnn-android-vulkan-shared
        key: ${{ runner.os }}-ncnn-20241226

    - name: Download NCNN and Assets
      run: |
        wget $ASSETS_URL -O assets.zip || true  # 允许 assets.zip 不存在
        mkdir -p 3rdparty
        if [ ! -d "3rdparty/ncnn-android-vulkan-shared" ]; then
          wget $NCNN_URL -O $NCNN_NAME
          unzip -o $NCNN_NAME -d 3rdparty/ncnn-android-vulkan-shared
        fi
        if [ -f "assets.zip" ]; then
          unzip -o assets.zip -d RealSR-NCNN-Android-GUI/app/src/main/assets
        fi

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git pkg-config \
            libavcodec-dev libavformat-dev libswscale-dev \
            libtbb-dev libjpeg-dev libpng-dev libtiff-dev \
            libgtk-3-dev libdc1394-dev libvulkan-dev

    - name: Build OpenCV (if not cached)
      if: steps.cache-opencv.outputs.cache-hit != 'true'
      run: |
        git clone https://github.com/opencv/opencv.git -b 4.9.0
        git clone https://github.com/opencv/opencv_contrib.git -b 4.9.0
        mkdir -p opencv/build && cd opencv/build
        cmake -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_INSTALL_PREFIX=/usr/local \
              -DOPENCV_EXTRA_MODULES_PATH=../../opencv_contrib/modules ..
        make -j$(($(nproc) - 1))
        sudo make install

    - name: Verify OpenCV installation
      run: |
        if [ ! -f "/usr/local/lib/cmake/opencv4/OpenCVConfig.cmake" ]; then
          echo "::error::OpenCV installation failed!"
          exit 1
        fi

    - name: Setup Java
      uses: actions/setup-java@v4.6.0
      with:
        distribution: temurin
        java-version: 21
        cache: gradle

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3.2.2

    - name: Build CLI
      run: |
        cd RealSR-NCNN-Android-CLI
        # 动态查找 CMakeLists.txt
        CMAKE_FILE=$(find . -name CMakeLists.txt | grep 'src/main/cpp/CMakeLists.txt')
        if [ -z "$CMAKE_FILE" ]; then
          echo "::error::CMakeLists.txt not found!"
          exit 1
        fi
        sed -i "s|set(OpenCV_DIR.*|set(OpenCV_DIR /usr/local/lib/cmake/opencv4)|" "$CMAKE_FILE"
        ./gradlew assembleDebug -PopenCV_DIR=/usr/local/lib/cmake/opencv4

    - name: Upload CLI artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: RealSR-NCNN-Android-CLI.zip
        path: RealSR-NCNN-Android-CLI/**/build/intermediates/cmake/release/obj/arm64-v8a
        retention-days: 90
